services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/corum/.docker/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=b86e9a8364a0c749f06616ca7cf174cbfae8c58b17fd31361048260b8a66c225
    ports:
      - '7575:7575'
